"""add deleted_at

Revision ID: 674e864d8c30
Revises: d40f40264827
Create Date: 2024-06-09 12:05:58.202228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674e864d8c30'
down_revision = 'd40f40264827'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'deleted_at')
    # ### end Alembic commands ###
